name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '50 5 * * *'
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy, rust-src
      - name: Build | Fmt Check
        run: cargo fmt -- --check
      - name: Build | Clippy
        run: cargo clippy --no-deps --workspace --all-features -- -Dwarnings
      - name: Build | Compile
        run: cargo build --workspace --all-features
