name: PublishCargoPioDryRun

on: workflow_dispatch

jobs:
  publishdryrun:
    name: Publish Dry Run
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rust-src
      - name: Build | Publish Dry Run
        run: cd cargo-pio; cargo publish --dry-run
